### ISSUE TITLE
PDF book: EC2AMI value never gets set

### ISSUE THREAD

**Issue by matthewhegarty** [dvassallo/aws-bootstrap#2]
I am working with Version 1.1, 2019-12-29

On page 74, the config has the `EC2AMI` value is defined:

```bash
  EC2AMI:
    Type: String
    Description: 'The EC2 AMI. Only tested on Amazon Linux 2.'
```

This is different to the value on page 57 where it is initially set:

```bash
EC2AMI:
  Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>' 
  Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
```

So by the time deployment is run (page 64), this value is not set.

In this repo I can see that it is passed in as a [param](https://github.com/good-parts/aws-bootstrap/blob/master/deploy/deploy-infra.sh#L53), so this may be a mistake in the book.  We either should not delete the Default, or we should pass `EC2AMI` in as a parameter.

The fix is to re-add the `Default` string

### Update

From page 122, Running `./deploy-infra.sh` fails with the error:

```
unable to fetch parameters [ami-xyz] from parameter store for this account
```

If you check the parameter store for the stack, then this value is present.

The fix is to [pass the AMI as a parameter override](https://github.com/good-parts/aws-bootstrap/blob/master/deploy/deploy-infra.sh#L53), eg:

```
EC2AMI=ami-01f14919ba412de34 \
```

The parameter has to be declared in `stage.yml` and `main.yml` as follows:

```yaml
Parameters:
  EC2AMI:
    Type: String
```

Also page 122, typo: "Within a few of minutes"

**Comment by dvassallo** [comment]
Fixed both. Thank you!
