### ISSUE TITLE
PDF book: First 'Release Change' fails on npm run

### ISSUE THREAD

**Issue by matthewhegarty** [dvassallo/aws-bootstrap#3]
Version 1.1

On page 82, the first deployment can take place by hitting "Release Change" in the console.  However this fails because there is no `npm test` target.

The fix is to remove the 'test' and 'build' commands from `buildspec.yml` (defined on page 71) and replace with `npm start`.

[aws_b_fail.log](https://github.com/good-parts/aws-bootstrap/files/4030909/aws_b_fail.log)

**Comment by dvassallo** [comment]
Fixed. Thank you!
